# Generated by Django 2.1 on 2020-03-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentclass', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('birthdate', models.CharField(max_length=50)),
                ('livesin', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=50)),
                ('siblings', models.CharField(max_length=100)),
                ('picture', models.CharField(max_length=500)),
                ('notes', models.CharField(max_length=1000)),
            ],
        ),
    ]
