# Generated by Django 2.1 on 2020-03-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='levels',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
