# Generated by Django 2.1 on 2020-03-13 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_levels_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='picture',
            field=models.ImageField(blank='True', upload_to='student_pictures'),
        ),
    ]
