# Generated by Django 2.1 on 2020-03-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_grade_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.IntegerField(blank=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.IntegerField(blank=0),
        ),
    ]
