# Generated by Django 2.1 on 2020-03-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20200320_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsLevelHistorical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentId', models.IntegerField(blank=0)),
                ('levelId', models.IntegerField(blank=0)),
                ('createdAt', models.DateTimeField(default='1900-01-01 00:00:00')),
                ('createdBy', models.CharField(default='admin', max_length=35)),
            ],
        ),
        migrations.AddField(
            model_name='grade',
            name='createdAt',
            field=models.DateTimeField(default='1900-01-01 00:00:00'),
        ),
        migrations.AddField(
            model_name='grade',
            name='createdBy',
            field=models.CharField(default='admin', max_length=35),
        ),
        migrations.AddField(
            model_name='grade',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grade',
            name='modifiedAt',
            field=models.DateTimeField(default='1900-01-01 00:00:00'),
        ),
        migrations.AddField(
            model_name='levels',
            name='createdAt',
            field=models.DateTimeField(default='1900-01-01 00:00:00'),
        ),
        migrations.AddField(
            model_name='levels',
            name='createdBy',
            field=models.CharField(default='admin', max_length=35),
        ),
        migrations.AddField(
            model_name='levels',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='levels',
            name='modifiedAt',
            field=models.DateTimeField(default='1900-01-01 00:00:00'),
        ),
        migrations.AddField(
            model_name='school',
            name='createdAt',
            field=models.DateTimeField(default='1900-01-01 00:00:00'),
        ),
        migrations.AddField(
            model_name='school',
            name='createdBy',
            field=models.CharField(default='admin', max_length=35),
        ),
        migrations.AddField(
            model_name='school',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='modifiedAt',
            field=models.DateTimeField(default='1900-01-01 00:00:00'),
        ),
        migrations.AddField(
            model_name='student',
            name='createdAt',
            field=models.DateTimeField(default='1900-01-01 00:00:00'),
        ),
        migrations.AddField(
            model_name='student',
            name='createdBy',
            field=models.CharField(default='admin', max_length=35),
        ),
        migrations.AddField(
            model_name='student',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='modifiedAt',
            field=models.DateTimeField(default='1900-01-01 00:00:00'),
        ),
    ]
