# Generated by Django 2.1 on 2020-03-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20200321_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='createdAt',
            field=models.DateTimeField(default='1900-01-01 00:00:00:000000'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='modifiedAt',
            field=models.DateTimeField(default='1900-01-01 00:00:00:000000'),
        ),
        migrations.AlterField(
            model_name='levels',
            name='createdAt',
            field=models.DateTimeField(default='1900-01-01 00:00:00:000000'),
        ),
        migrations.AlterField(
            model_name='levels',
            name='modifiedAt',
            field=models.DateTimeField(default='1900-01-01 00:00:00:000000'),
        ),
        migrations.AlterField(
            model_name='school',
            name='createdAt',
            field=models.DateTimeField(default='1900-01-01 00:00:00:000000'),
        ),
        migrations.AlterField(
            model_name='school',
            name='modifiedAt',
            field=models.DateTimeField(default='1900-01-01 00:00:00:000000'),
        ),
        migrations.AlterField(
            model_name='student',
            name='createdAt',
            field=models.DateTimeField(default='1900-01-01 00:00:00:000000'),
        ),
        migrations.AlterField(
            model_name='student',
            name='modifiedAt',
            field=models.DateTimeField(default='1900-01-01 00:00:00:000000'),
        ),
        migrations.AlterField(
            model_name='studentslevelhistorical',
            name='createdAt',
            field=models.DateTimeField(default='1900-01-01 00:00:00:000000'),
        ),
    ]
