# Generated by Django 2.1 on 2020-03-22 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20200321_0905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='birthdate',
            new_name='birthDate',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='livesin',
            new_name='livesIn',
        ),
    ]
