# Generated by Django 2.1 on 2020-03-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20200322_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='picture',
            field=models.CharField(max_length=100),
        ),
    ]
