# Generated by Django 2.1 on 2020-03-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_auto_20200324_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='deleted',
        ),
        migrations.AddField(
            model_name='school',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
